#!python
from os import environ

bind = "0.0.0.0:%s" % (environ.get('PORT'),)
workers = 1
timeout = 30
worker_class = 'gevent'

def on_starting(server):
    # for a server with such a nice hooking framework, gunicorn sure has odd logging customization;
    # I found it /much/ easier to do this change from here than using logger_class
    server.log.error_fmt = r"[%(process)05d] [%(levelno)02d] gunicorn   %(message)s"
    server.log.setup(server.app.cfg)
